/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */
plugins {
    kotlin("jvm") version "1.9.22"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    // We're not using the plugin-yml-bukkit plugin anymore since we're providing our own plugin.yml
}

group = "zepsizola.me"
version = "1.6"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT")
    compileOnly("net.kyori:adventure-text-minimessage:4.15.0")
    compileOnly(kotlin("stdlib"))
    implementation("org.bstats:bstats-bukkit:3.0.2")
}

tasks {
    compileKotlin {
        kotlinOptions.jvmTarget = "17"
    }
    
    compileJava {
        options.release.set(17)
    }
    
    shadowJar {
        relocate("org.bstats", "me.zepsizola.zInvisItemFrames.bstats")
        archiveVersion.set(project.version.toString())
        archiveClassifier.set("")
        minimize()
    }

    processResources {
        val props = mapOf("version" to project.version)
        inputs.properties(props)
        filteringCharset = "UTF-8"
        filesMatching("plugin.yml") {
            expand(props)
        }
    }
    
    build {
        dependsOn(shadowJar)
    }
}
